org.gradle.daemon=false
org.gradle.debug=false
#########################################################
# Minecraft Versions                                    #
#########################################################
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.75
neo_version_range=[26.1.2.75,)
#########################################################
# Integration Versions                                  #
#########################################################
jei_version=29.6.2.31
#########################################################
# Mod Info                                              #
#########################################################
loader_version_range=[1,)
mod_id=nucleus_pauljoda
mod_name=Nucleus
mod_license=All Rights Reserved
mod_version=3.1.2
mod_group_id=com.pauljoda.nucleus
mod_authors=pauljoda, Dyonovan
mod_description=Library mod for pauljoda mods
